import{a as h,i as q,S as E}from"./assets/vendor-527658dd.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const y=15;h.defaults.baseURL="https://pixabay.com/api/";const P="42471453-a4a004408e33f852748a0909e";async function L(a,s){const o="photo",i="horizontal",{data:t}=await h.get("",{params:{page:a,per_page:y,key:P,q:s,image_type:o,orientation:i,safesearch:!0}});return t}function v(a,s){const o=a.map(({webformatURL:i,largeImageURL:e,tags:t,likes:n,views:I,comments:b,downloads:w})=>`<li class="image-search">
        <a href="${e}">
        <img class="gallery-image" src="${i}" alt="${t}"/>
        </a>
        <ul class="gallery-image-info">
          <li class="image-items">
            <p class="image-info-items"><span class="image-items-text">Likes</span>${n}</p>
            <p class="image-info-items"><span class="image-items-text">Views</span>${I}</p>
            <p class="image-info-items"><span class="image-items-text">Comments</span>${b}</p>
            <p class="image-info-items"><span class="image-items-text">Downloads</span>${w}</p>
          </li>
        </ul>
      </li>`).join("");s.insertAdjacentHTML("beforeend",o)}function l(a,s,o){q.info({position:"topRight",message:a,iconUrl:o,messageColor:"#ffffff",backgroundColor:s,messageSize:16,layout:2,maxWidth:380,theme:"dark"})}const S=new E(".gallery-list a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".loading"),c=document.querySelector(".form-container div"),p=document.querySelector("input"),u=document.querySelector("form"),r=document.querySelector(".load-more-img"),g=document.querySelector(".gallery-list");let d=1,f;r.classList.add("hidden");u.addEventListener("submit",x);async function x(a){if(a.preventDefault(),d=1,f=p.value,g.innerHTML="",r.classList.add("hidden"),p.value.trim()===""){r.classList.add("hidden"),l("Sorry, input is emty. Please try again!","#FFA000");return}c.classList.add("loader");try{const s=await L(d,f);if(s.total===0){l("Sorry, there are no images matching your search query. Please try again!","#EF4040",cross),c.classList.remove("loader"),r.classList.add("hidden"),u.reset();return}v(s.hits,g),c.classList.remove("loader"),r.classList.remove("hidden"),S.refresh()}catch{l("Something went wrong.Please try later")}u.reset()}r.addEventListener("click",$);async function $(){d+=1,m.classList.add("loader"),r.classList.add("hidden");try{const a=await L(d,f);if(v(a.hits,g),c.classList.remove("loader"),m.classList.remove("loader"),r.classList.remove("hidden"),window.scrollBy({top:575.6666870117188,behavior:"smooth"}),a.hits.length<y)return r.classList.add("hidden"),l("We're sorry, but you've reached the end of search results.","#0071BD");S.refresh()}catch{m.classList.remove("loader"),l("You have more 100 requests per minute.Please try later")}}
//# sourceMappingURL=commonHelpers.js.map
